version: '3'
services:
    zoo:
        image: zookeeper
        restart: always
        container_name: zookeeper_1
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=182.92.3.187:2888:3888 server.2=182.92.160.62:2888:3888 server.3=39.96.42.239:2888:3888
